force-app/main/default/objects/Earthquake__c/Earthquake__c.object-meta.xml
<CustomObject>
    <label>Earthquake</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Earthquake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Earthquakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Earthquake__c/fields/Alert_Level__c.field-meta.xml
<CustomField>
    <fullName>Alert_Level__c</fullName>
    <label>Alert Level</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Earthquake__c/fields/Depth__c.field-meta.xml
<CustomField>
    <fullName>Depth__c</fullName>
    <label>Depth</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Earthquake__c/fields/Magnitude__c.field-meta.xml
<CustomField>
    <fullName>Magnitude__c</fullName>
    <label>Magnitude</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Earthquake__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <label>Place</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Earthquake__c/fields/USGS_ID__c.field-meta.xml
<CustomField>
    <fullName>USGS_ID__c</fullName>
    <label>USGS ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Earthquake__c/fields/USGS_Link__c.field-meta.xml
<CustomField>
    <fullName>USGS_Link__c</fullName>
    <label>USGS Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/GEO_Earthquake_Save.cls
public with sharing class GEO_Earthquake_Save extends GEO_Base {
  public class EQBlueprintx {
    public String id;
    public Double mag;
    public String alert;
    public String place;
    public Double longitude;
    public Double latitude;
    public Double depth;
    public String url;
  }

  public class NoteBluprint {
    public String text1;
    public String earthquakeId;
  }

  @AuraEnabled
  public static string saveEarthquakeRecord(String earthquakeDetailsString) {
    EQBlueprintx eqObject = (EQBlueprintx) JSON.deserializeStrict(
      earthquakeDetailsString,
      EQBlueprintx.class
    );

    Earthquake__c eq = new Earthquake__c();

    eq.USGS_ID__c = eqObject.id;
    eq.Magnitude__c = eqObject.mag;
    eq.Place__c = eqObject.place;
    eq.Alert_Level__c = eqObject.alert;
    eq.Depth__c = eqObject.depth;
    eq.USGS_Link__c = eqObject.url;
    eq.Geolocation__longitude__s = eqObject.longitude;
    eq.Geolocation__latitude__s = eqObject.latitude;

    system.debug(eqObject);

    insert eq;

    return eq.Id;
  }

  @AuraEnabled
  public static string saveEarthquakeNoteRecord(String earthquakeNoteString) {
    NoteBluprint noteObject = (NoteBluprint) JSON.deserializeStrict(
      earthquakeNoteString,
      NoteBluprint.class
    );

    Earthquake_Note__c en = new Earthquake_Note__c();
    en.Text_Field__c = noteObject.text1;
    en.Earthquake__c = noteObject.earthquakeId;

    insert en;

    return 'Success! Earthquake Note record';
  }

  @AuraEnabled(cacheable=true)
  public static List<Earthquake__c> isEarthquakeSaved(String earthquakeUsgsId) {
    return [
      SELECT Id
      FROM Earthquake__c
      WHERE USGS_ID__c = :earthquakeUsgsId
    ];
  }

  @AuraEnabled(cacheable=true)
  public static List<Earthquake_Note__c> retrieveNotes(
    String earthquakeId,
    Integer wireMethodActivation
  ) {
    Integer testNumber = wireMethodActivation;
    return [
      SELECT
        Id,
        Text_Field__c,
        CreatedDate,
        CreatedById,
        Earthquake__r.Id,
        CreatedBy.Name
      FROM Earthquake_Note__c
      WHERE Earthquake__c = :earthquakeId
      ORDER BY CreatedDate DESC
    ];
  }
}